# Generated by Django 5.0.6 on 2024-07-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AddField(
            model_name='user',
            name='town',
            field=models.CharField(max_length=50, null=True, verbose_name='Город'),
        ),
    ]
