# Generated by Django 5.0.6 on 2024-07-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('c', 'cash'), ('t', 'transfer')], default='s', max_length=1, verbose_name='Тип оплаты'),
        ),
    ]
