# Generated by Django 5.0.6 on 2024-07-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payment_options_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('c', 'cash'), ('t', 'transfer')], default='c', max_length=1, verbose_name='Тип оплаты'),
        ),
    ]
