# Generated by Django 5.0.6 on 2024-07-08 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='materials.course', verbose_name='Курс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='link',
            field=models.CharField(default='', max_length=200, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
