# Generated by Django 5.0.6 on 2024-07-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_course_img_alter_lesson_img_alter_lesson_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка'),
        ),
    ]
